repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.0post1
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        additional_dependencies:
        -   tomli

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
    -   id: ruff

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
    -   id: gitleaks
