select = [
    "F",     # Pyflakes (F)
    "E",     # pycodestyle Error (E)
    "W",     # pycodestyle Warning (W)
    "C90",   # mccabe (C90)
    "I",     # isort (I)
    "N",     # pep8-naming (N)
    "UP",    # pyupgrade (UP)
    "YTT",   # flake8-2020 (YTT)
    "ASYNC", # flake8-async (ASYNC)
    "S",     # flake8-bandit (S)
    "BLE",   # flake8-blind-except (BLE)
    "B",     # flake8-bugbear (B)
    "A",     # flake8-builtins (A)
    "COM",   # flake8-commas (COM)
    "C4",    # flake8-comprehensions (C4)
    "DTZ",   # flake8-datetimez (DTZ)
    "T10",   # flake8-debugger (T10)
    "DJ",    # flake8-django (DJ)
    "EM",    # flake8-errmsg (EM)
    "EXE",   # flake8-executable (EXE)
    "FA",    # flake8-future-annotations (FA)
    "ISC",   # flake8-import-conventions (ICN)
    "ICN",   # flake8-import-conventions (ICN)
    "G",     # flake8-logging-format (G)
    "INP",   # flake8-no-pep420 (INP)
    "PIE",   # flake8-pie (PIE)
    "T20",   # flake8-print (T20)
    "PYI",   # flake8-pyi (PYI)
    "PT",    # flake8-pytest-style (PT)
    "Q",     # flake8-quotes (Q)
    "RSE",   # flake8-raise (RSE)
    "RET",   # flake8-return (RET)
    "SLF",   # flake8-self (SLF)
    "SLOT",  # flake8-slots (SLOT)
    "SIM",   # flake8-simplify (SIM)
    "TID",   # flake8-tidy-imports (TID)
    "TCH",   # flake8-type-checking (TCH)
    "INT",   # flake8-gettext (INT)
    "ERA",   # eradicate (ERA)
    "PD",    # pandas-vet (PD)
    "PGH",   # pygrep-hooks (PGH)
    "PL",    # Pylint (PL)
    "TRY",   # tryceratops (TRY)
    "FLY",   # flynt (FLY)
    "NPY",   # NumPy-specific rules (NPY)
    "AIR",   # Airflow (AIR)
    "PERF",  # Perflint (PERF)
    "RUF"    # Ruff-specific rules (RUF)
]

# Ignored rules
#    "ANN",   # flake8-annotations (ANN)
#    "ARG",   # flake8-unused-arguments (ARG)
#    "D",     # pydocstyle (D)
#    "PTH",   # flake8-use-pathlib (PTH)
#    "BLE",   # flake8-blind-except (BLE)
#    "FBT",   # flake8-boolean-trap (FBT)
#    "TD",    # flake8-todos (TD)
#    "FIX"    # flake8-fxme (FIX)
#    "CPY",   # flake8-copyright (CPY)


# Ignore error code
ignore = []
