repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # E501 - ignore line length
        # W503 - ignore line break before binary operator => cause conflict with BLACK
        # F401 - ignore imported but unused
        args: ["--ignore=E501,W503,F401"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
            - -L hass
        exclude_types: [csv, json]
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args:
          # E0401 - ignore Unable to import
          - --disable=E0401
          - --fail-under=7
          - --rcfile=./.pylintrc
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.2.1
    hooks:
        -   id: pycln
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --quiet
