go_to_location:
  name: Go to location
  description: Sends robot to an (X, Y) location.
  target:
    integration: vacuum
  fields:
    point:
      name: Destination point
      description: Point in format [x,y]
      required: true